### ISSUE TITLE
How to set up an icon for a RibbonButton with C# code？

### ISSUE THREAD

**Issue by nasterhe** [dmitryzarubin/Ribbon.Avalonia#1]
The icon type of the RibbonButton is IControlTemplate, how to set it through the C# code? Thanks.

**Comment by dmitryzarubin** [comment]
Hello, @nasterhe 

You can use FuncControlTemplate to create a control template in c# code.
     
```
var uri = new Uri("avares://Ribbon.Avalonia.Sample/Assets/boxIconLarge.png");
var stream = AssetLoader.Open(uri);
var source = new Bitmap(stream);
            
ribbonButton.LargeIcon = new FuncControlTemplate((templatedControl, scope) =>
{
     return new Image() { Source = source };
});
```

However, it is generally better to declare all assets in your application's resources and bind them to icon properties. You can find an example in the Ribbon.Avalonia.Sample project within this repository.

**Comment by nasterhe** [comment]
Hello，@dmitryzarubin 
Thank you for your reply.
The code you provided works fine for RibbonButton and RibbonSplitButton, but the RibbonDropDownButtonItem crashes when I click the dropdown next to the RibbonSplitButton after setting the Icon the way you said.

**Comment by dmitryzarubin** [comment]
@nasterhe Could you provide more details about the crash, such as a stack trace or a code sample?

**Comment by nasterhe** [comment]
Your reply was very helpful to me, I debugged repeatedly and finally found the cause of the crash, because one of my png files does not exist, thank you.

**Comment by dmitryzarubin** [comment]
Closed
